### ISSUE TITLE
As a user I want the API to keep an internal state of my nonces

### ISSUE THREAD

**Issue by Evert0x** [thxprotocol/api#44]
EVM transaction will fail using the GasStation if the same nonce is used. If `getLatestNonce` is used for every call, it could be the case a transaction is already pending and the same nonce is used twice.

Keeping an internal state will always get the right nonce.

Especially because the GasStation can only be called by the API.

**Comment by Evert0x** [comment]
The nonce is per Ethereum address for every call made to the `GasStation`

**Comment by peterpolman** [comment]
Due to ITX not always persisting the order of received transactions (and since we require the order to be persistent due to the nonce for calls made from the admin account), we are forced to send them serially now anyway. Resulting in getLatestNonce() always returning the "latest nonce". Closing for now, might re-open when optimising the queue processor.
